// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBJz7aAQoy-6SbrPjpV43hUCd6AhVV2Lk4',
    appId: '1:526028484568:android:bdd17a70f17e7ed77accad',
    messagingSenderId: '526028484568',
    projectId: 'chat-app-304d9',
    storageBucket: 'chat-app-304d9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDK9zYevhSKKQzeRJ-uVuk01COOHGQ4eQY',
    appId: '1:526028484568:ios:352126026ae0580a7accad',
    messagingSenderId: '526028484568',
    projectId: 'chat-app-304d9',
    storageBucket: 'chat-app-304d9.appspot.com',
    androidClientId: '526028484568-ft7nnrl5his4vv26ogsd2focgeau035o.apps.googleusercontent.com',
    iosClientId: '526028484568-vte3nb157l3fg93pepnbbb8c34do2g6v.apps.googleusercontent.com',
    iosBundleId: 'com.chatapplication.flutterProjectChatApplication',
  );

}